const QUOTES = [
  { text: "The groundwork of all happiness is health.", author: "Leigh Hunt" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "To keep the body in good health is a duty, otherwise we shall not be able to keep our mind strong and clear.", author: "Buddha" },
  { text: "A healthy outside starts from the inside.", author: "Robert Urich" },
  { text: "Your body is your most priceless possession; take care of it.", author: "Jack LaLanne" },
  { text: "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.", author: "John F. Kennedy" },
  { text: "Good posture can be successfully acquired only when the entire mechanism of the body is under perfect control.", author: "Joseph Pilates" },
  { text: "Movement is a medicine for creating change in a person's physical, emotional, and mental states.", author: "Carol Welch" },
  { text: "The first wealth is health.", author: "Ralph Waldo Emerson" },
  { text: "It is health that is real wealth and not pieces of gold and silver.", author: "Mahatma Gandhi" },
  { text: "Your body hears everything your mind says.", author: "Naomi Judd" },
  { text: "An ounce of prevention is worth a pound of cure.", author: "Benjamin Franklin" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Small steps in the right direction can turn out to be the biggest step of your life.", author: "Unknown" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Health is not about the weight you lose, but about the life you gain.", author: "Unknown" },
  { text: "Take care of your body, it's the only home you'll ever live in.", author: "John Rohn" },
  { text: "A good stance and posture reflect a proper state of mind.", author: "Morihei Ueshiba" },
  { text: "Sitting is the new smoking.", author: "Dr. James Levine" },
  { text: "The doctor of the future will give no medicine, but will interest his patients in the care of the human frame.", author: "Thomas Edison" },
];
