const QUOTES = [
  // Health & posture
  { text: "The groundwork of all happiness is health.", author: "Leigh Hunt" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Good posture can be successfully acquired only when the entire mechanism of the body is under perfect control.", author: "Joseph Pilates" },
  { text: "The first wealth is health.", author: "Ralph Waldo Emerson" },
  { text: "It is health that is real wealth and not pieces of gold and silver.", author: "Mahatma Gandhi" },
  { text: "A good stance and posture reflect a proper state of mind.", author: "Morihei Ueshiba" },
  { text: "Sitting is the new smoking.", author: "Dr. James Levine" },
  { text: "Your body hears everything your mind says.", author: "Naomi Judd" },
  { text: "An ounce of prevention is worth a pound of cure.", author: "Benjamin Franklin" },
  // Pure motivational
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Whether you think you can or you think you can't — you're right.", author: "Henry Ford" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "Dream it. Wish it. Do it.", author: "Unknown" },
  { text: "Stay focused and never give up.", author: "Unknown" },
  { text: "Work hard in silence, let success make the noise.", author: "Frank Ocean" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
  { text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson" },
  { text: "The harder I work, the luckier I get.", author: "Gary Player" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { text: "Little by little, a little becomes a lot.", author: "Tanzanian Proverb" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
];
